services:
  caddy:
    image: caddy:2.8
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      - CADDY_LISTEN=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    
      
  database:
    image: postgis/postgis:13-master
    restart: always
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD_FILE: "/run/secrets/database_password"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    secrets: 
      - database_password

  directus:
    build: ./directus 
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET_FILE: '/run/secrets/directus_secret'
      PUBLIC_URL: 'https://monaslyceedirectus.bhdev.org'
      CORS_ENABLED: 'true'
      # CORS_ORIGIN: '*'
      CORS_ORIGIN: 'https://monaslyceeoffice.bhdev.org,https://unsubscribemonaslycee.bhdev.org,https://monaslyceeresetpassword.bhdev.org'
      WEBSOCKETS_ENABLED: 'true'
      LOG_LEVEL: 'error'

      EMAIL_TRANSPORT: 'smtp'
      EMAIL_FROM: 'no-reply@bhdev.org'
      EMAIL_SMTP_HOST: 'mail.your-server.de'
      EMAIL_SMTP_PORT: '587'
      EMAIL_SMTP_USER: 'no-reply@bhdev.org'
      EMAIL_SMTP_PASSWORD: '93cjLHvV83Bkv6PH'
      PASSWORD_RESET_URL_ALLOW_LIST: 'https://monaslyceeresetpassword.bhdev.org'

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD_FILE: '/run/secrets/database_password'

      CACHE_ENABLED: "false"

      ADMIN_EMAIL: "adminlycee@example.com"
      ADMIN_PASSWORD_FILE: "/run/secrets/directus_admin_password"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
    secrets:
      - database_password
      - directus_secret
      - directus_admin_password
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8055/_/health"]
      interval: 30s
      timeout: 10s
      retries: 3
     
    

    # Environment variables can also be defined in a file (for example `.env`):
    # env_file:
    # - .env
secrets:
  database_password:
    file: ./secrets/database_password.txt
  directus_secret:
    file: ./secrets/directus_secret.txt
  directus_admin_password:
    file: ./secrets/directus_admin_password.txt

# volumes:
#   redis_data:
